import '../styles/global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full w-full">
      <head>
        <link href='./font.woff2' rel="preload" as='font' type='font/woff2' crossOrigin="" />
        <title>Decl Modal Next.js - Nazfy</title>
        <meta name='description' content='Prueba Decl Modal Next js app router, page route.'/>
        {/* icon */}
        <link
          rel="apple-touch-icon-precomposed"
          sizes="57x57"
          href="/fav/apple-touch-icon-57x57.png"
        />
        <link
          rel="apple-touch-icon-precomposed"
          sizes="114x114"
          href="/fav/apple-touch-icon-114x114.png"
        />
        <link
          rel="apple-touch-icon-precomposed"
          sizes="72x72"
          href="/fav/apple-touch-icon-72x72.png"
        />
        <link
          rel="apple-touch-icon-precomposed"
          sizes="144x144"
          href="/fav/apple-touch-icon-144x144.png"
        />
        <link
          rel="apple-touch-icon-precomposed"
          sizes="60x60"
          href="/fav/apple-touch-icon-60x60.png"
        />
        <link
          rel="apple-touch-icon-precomposed"
          sizes="120x120"
          href="/fav/apple-touch-icon-120x120.png"
        />
        <link
          rel="apple-touch-icon-precomposed"
          sizes="76x76"
          href="/fav/apple-touch-icon-76x76.png"
        />
        <link
          rel="apple-touch-icon-precomposed"
          sizes="152x152"
          href="/fav/apple-touch-icon-152x152.png"
        />
        <link
          rel="icon"
          type="image/png"
          href="/fav/favicon-196x196.png"
          sizes="196x196"
        />
        <link rel="icon" type="image/png" href="/fav/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/png" href="/fav/favicon-32x32.png" sizes="32x32" />
        <link rel="icon" type="image/png" href="/fav/favicon-16x16.png" sizes="16x16" />
        <link rel="icon" type="image/png" href="/fav/favicon-128.png" sizes="128x128" />
        <meta name="application-name" content=" " />
        <meta name="msapplication-TileColor" content="#FFFFFF" />
        <meta name="msapplication-TileImage" content="/fav/mstile-144x144.png" />
        <meta name="msapplication-square70x70logo" content="/fav/mstile-70x70.png" />
        <meta
          name="msapplication-square150x150logo"
          content="/fav/mstile-150x150.png"
        />
        <meta name="msapplication-wide310x150logo" content="/fav/mstile-310x150.png" />
        <meta
          name="msapplication-square310x310logo"
          content="/fav/mstile-310x310.png"
        />

      </head>
      <body className="h-full w-full">{children}</body>
    </html>
  );
}
