name: 'Playwright CI'
on: 
  push:
    branches:
      - main
    paths: 
      - 'packages/dependency/**'

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '20.9.0'
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm i
      - name: Install playwright browsers
        run: cd packages/tests && npx playwright install --with-deps
      - name: release core
        run: cd packages/dependency/core && npm run release
      - name: release react
        run: cd packages/dependency/react && npm run release
      - name: release svelte
        run: cd packages/dependency/svelte && npm run release
      - name: Dev mode React app
        run: cd packages/examples/nextjs-app-pages-router && npm run dev & npx wait-on http://localhost:3000 --timeout 60000 && cd packages/examples/first_svelte_app && npm run dev & npx wait-on http://localhost:5173 --timeout 60000 && cd packages/tests && npx playwright test
        env:
          CI: true