name: 'First ci test'
on: 
  push:
    branches:
      - main
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm i
      - name: Install playwright browsers
        run: cd packages/tests && npx playwright install --with-deps
      - name: Dev mode React app
        run: cd packages/examples/nextjs-app-pages-router && npm run dev & cd ../../../ npx wait-on http://localhost:3000
      - name: Dev mode Svelte app
        run: 
          cd packages/examples/first_svelte_app && npm run dev & cd ../../../ npx wait-on http://localhost:5173
      - name: Run tests
        run: cd packages/tests && npx playwright test